import bz2
import numpy as np
import matplotlib.pyplot as plt

fb = '201605100300.vis.01.fld.geoss.bz2'
bfb = np.frombuffer(bz2.BZ2File(fb).read())
bfb.shape
    (36000000,)
bfb = (bfb.reshape(3000, 2, 3000, 2).mean(-1).mean(1) + 0.5).astype('u2')
    <stdin>:1: RuntimeWarning: invalid value encountered in cast

fg = '201605100300.vis.02.fld.geoss.bz2'
bfg = np.frombuffer(bz2.BZ2File(fg).read())
bfg = (bfg.reshape(3000, 2, 3000, 2).mean(-1).mean(1) + 0.5).astype('u2')

fr = '201605100300.ext.01.fld.geoss.bz2'
bfr = np.frombuffer(bz2.BZ2File(fr).read())
bfr = (bfr.reshape(3000, 4, 3000, 4).mean(-1).mean(1) + 0.5).astype('u2')

rgb = np.dstack((bfr, bfg, bfb))
rgb.shape
(3000, 3000, 3)
rgb.dtype
dtype('uint16')

plt.imshow(rgb)
    Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
    <matplotlib.image.AxesImage object at 0x00000159F21B84A0>
count, value = np.loadtxt('../count2tbb_v103/vis.01', unpack = True)
vb = value[bfb]
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    IndexError: index 39432 is out of bounds for axis 0 with size 2048
